# Nom du workflow
name: Générer le Zip et créer une PR sur le site web

# --- DÉCLENCHEUR ---
# Se déclenche sur les Pull Requests vers la branche main du dépôt DIMA
on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize]

# --- TÂCHES (JOBS) ---
jobs:
  build-and-create-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: read # On a juste besoin de lire le dépôt courant

    steps:
      # Étape 1 : Récupère le code du dépôt DIMA (celui de la PR)
      - name: 1. Récupération du code de DIMA
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      # Étape 2 : Crée l'archive .zip
      - name: 2. Compression du répertoire du plugin
        run: |
          cd "plugin/plugin_chrome/releases/"
          zip -r Plugin-dima.zip Plugin-dima

      # Étape 3 : Clone le dépôt M82-SiteWeb
      - name: 3. Récupération du dépôt M82-SiteWeb
        uses: actions/checkout@v4
        with:
          repository: M82-project/M82-SiteWeb
          token: ${{ secrets.CROSS_REPO_PAT }}
          path: M82-SiteWeb

      # Étape 4 : Copie le zip dans le dépôt du site web
      - name: 4. Copie du fichier .zip
        run: |
          mv plugin/plugin_chrome/releases/Plugin-dima.zip M82-SiteWeb/static/files/

      # Étape 5 : Crée une Pull Request dans M82-SiteWeb
      - name: 5. Création de la Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          # Spécifie le dépôt dans lequel on travaille
          path: ./M82-SiteWeb
          # Le PAT est indispensable pour créer une PR dans un autre dépôt
          token: ${{ secrets.CROSS_REPO_PAT }}
          # Nom de la nouvelle branche qui sera créée dans M82-SiteWeb
          branch: "update/plugin-dima-zip"
          # Titre de la Pull Request
          title: "🤖 Mise à jour automatique du Plugin-dima.zip"
          # Description de la Pull Request
          body: |
            Mise à jour du fichier `Plugin-dima.zip`.
            Cette modification a été déclenchée automatiquement par un workflow du dépôt `DIMA`.
          # Message du commit
          commit-message: "feat: Mise à jour du Plugin-dima.zip"
          # La branche de base sur laquelle la PR doit être faite
          base: master
