# Nom du workflow qui apparaîtra dans l'onglet "Actions" de votre dépôt GitHub
name: Créer l'archive du plugin

# --- DÉCLENCHEUR ---
on:
  push:
    branches:
      - main

# --- TÂCHES (JOBS) ---
jobs:
  zip-and-commit:
    runs-on: ubuntu-latest

    # AJOUTEZ CECI : Donne la permission d'écrire dans le dépôt
    permissions:
      contents: write

    # --- ÉTAPES (STEPS) ---
    steps:
      - name: 1. Récupération du code
        uses: actions/checkout@v4

      - name: 2. Compression du répertoire en .zip
        run: |
          cd "plugin/plugin_chrome/releases/"
          zip -r Plugin-dima.zip Plugin-dima
      
      - name: 3. Commit de l'archive sur le dépôt
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "🤖 CI : Mise à jour automatique de l'archive Plugin-dima.zip"
          file_pattern: 'plugin/plugin_chrome/releases/Plugin-dima.zip'
